### ISSUE TITLE
Contribuidores

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#1]
Se observa que los integrantes han realizado `fork` del repositorio. ¿Será esta la metodología de trabajo o aún no se han agregado al repositorio como contribuidores?  
No se observa aún desarrollo funcional.

**Comment by dario-castano** [comment]
Se cambio de forks a agregar contributors. Todos tienen autorización para hacer push a excepción de un integrante que no se ha reportado
