### ISSUE TITLE
Contribuidores

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#11]
El archivo `README.md` enuncia a 5 contribuidores, pero la [lista de contribuidores del repositorio muestra 4](https://github.com/dario-castano/miniCAS/graphs/contributors).

**Comment by dario-castano** [comment]
Se debe a que el usuario https://github.com/GeraldineE no ha hecho aportes al repositorio hasta el momento. Tal vez por eso no salga en la lista de contribuyentes
