### ISSUE TITLE
Ausencia de funcionalidad (y commits funcionales)

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#16]
A pesar del gran número de `commit`s presentes, actualmente este repositorio no se encuentra funcional en el sentido evaluativo.
No existe avance real en ninguna de las funciones solicitadas como evaluación.
Se debe tener en cuenta que este es un taller de álgebra computacional, así que lo funcional que se aporte para que funcione es justo en el álgebra computacional. Para el funcionamiento de este taller es incluso posible prescindir del desarrollo de clases y de pruebas unitarias, por lo cual al momento, realmente no hay `commit`s funcionales.
No hay nada en el momento, a pesar de la definición del constructor de clases, que permita al momento, si un número dado en cadena de caracteres pertenece a los enteros, fraccionarios o racionales (`isZ`, `isF` y `isQ`). Y a raíz de lo mismo, menos que hay funcionalidad asociada a `simplify`.
La definición de una clase por si misma no aporta al álgebra computacional, ya que lo que permite que dicha clase sea admisible en el álgebra computacional no es la estructura de datos para su almacenamiento y representación sino los métodos que actúan sobre las clases.
Igualmente las pruebas unitarias por si mismas solo son validaciones, lo cual implica que la lógica que intervino en su desarrollo nunca requirió de mostrar conocimiento de formas de implementación del álgebra computacional, ya que los validadores dependen de patrones dados por los casos de prueba, y se compara a nivel de salidas, o sea, que no se aportó al desarrollo.
Esto representa tras el escrutinio de las participaciones actuales, que ningún `commit` clasifica como funcional para el taller de álgebra computacional.
Este reporte refuerza las indicaciones requeridas en #14 y #15 , e invita a mejorar las descripciones de los `commit` para dar claridad en el proceso evaluativo para todos de lo que se aportó funcionalmente (asociado al reporte #13 ).

**Comment by cosmoscalibur** [comment]
@DanielBetancur presenta `commit`s funcionales pero no se encuentran dispuestos en el repositorio presentado como taller sino en un [`fork`](https://github.com/DanielBetancur/miniCAS). Requiere hacer solicitud de PR o pasar manualmente los archivos al repositorio que todos usan.

**Comment by DanielBetancur** [comment]
corregido

**Comment by cosmoscalibur** [comment]
@DanielBetancur creaste duplicado de la clase Entero. Existen ahora dos archivos para la clase. Igualmente el nuevo archivo presenta incumplimiento de una de las normas, la cual esta reportada en #12 . Y acorde al diseño planeado por el equipo estarías cayendo en el reporte #3 .

**Comment by cosmoscalibur** [comment]
Ya se encuentran `commit`s funcionales de al menos dos integrantes del equipo.
