### ISSUE TITLE
Descripción archivo de clases y clases inexistentes referenciadas

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#2]
El [archivo de clases](https://github.com/dario-castano/miniCAS/blob/master/Classes.py) hace referencia en la implementación de la clase de enteros a clases no definidas, las cuales tampoco se describen en su funcionamiento.  

Por otro lado, conviene para claridad en estos comportamientos que el código se encuentre comentado para ilustrar lo que se realiza.

**Comment by dario-castano** [comment]
Se asigna este issue al encargado de la clase de enteros
