### ISSUE TITLE
Ausencia de Aritmética exacta

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#4]
Se observa en la implementación actual que no se esta cumpliendo con que sus resultados puedan ser eventualmente exactos.
Se esta dependiendo de números expresados como `float` para la validación decimal.  Igualmente se encuentran casos de conversión usando `float`. Se usa continuamente conversión `int` de valores que ademas ya son números, entendiendose una conversión de flotantes a enteros en este caso.
Partir del uso de flotantes implica usar valores que fueron ya aproximados al conjunto de números representables en la máquina. De hecho, significa problemas para valores con más de 16 cifras e incluso la imposibilidad de distinguir enteros dados como racionales de representación decimal o incluso distinguir un entero de un racional muy cercano (probar en python `3 == 2.9999999999999999`).

**Comment by dario-castano** [comment]
Se asigna el problema al encargado de la función Decimal

**Comment by dario-castano** [comment]
¿Se encuentra el mismo problema en la clase  Entero?

**Comment by cosmoscalibur** [comment]
Hay uso de `float` en más de un archivo.

**Comment by dario-castano** [comment]
Se configura la clase decimal para que funcione a base de arreglos de strings. Se soluciona en commit 53cd3faed662d0a91271c9319d2706c670b5858a

**Comment by cosmoscalibur** [comment]
Sin embargo el problema no estaba presente solo en dicha clase. La conversión de fraccionarios a decimales se encuentra verdadera cuando no es entero lo cual afecta si la fracción es de representación decimal periodica. Adicional, hace uso de `float` lo cual repredenta no solo un uso prohibido sino tambien perdida de aritmetica exacta.
