### ISSUE TITLE
Uso injusttificado y abusivo de `int`.

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#5]
Existe un uso abusivo e injustificado de la conversión `int` en cantidades que en teoría son números, e incluso más exactamente que son enteros en algunos casos, por lo cual no es comprensible el abuso de las conversiones o si esto proviene de un caso de `copy paste` y por ello la inconsistencia. Por ejemplo, la definición del máximo común divisor, función `mcd`, es solo para enteros, sin embargo están forzando la conversión de su salida a entero nuevamente. Igualmente existen conversiones que dependen de conversiones de enteros donde se observa que posee igual un residuo numérico, cuando acorde a las especificaciones del taller solo estarían usando _strings_ o enteros, luego si el dato ya es numérico, solo podrían estar convirtiendo un entero a entero.

**Comment by dario-castano** [comment]
Se asgina al encargado de la clase Fraccionario. ¿Se presenta este problema fuera de la clase Fraccionario?

**Comment by cosmoscalibur** [comment]
No fue observado por fuera en la revisión que realice
