### ISSUE TITLE
Conversión ciclica

### ISSUE THREAD

**Issue by cosmoscalibur** [dario-castano/miniCAS#8]
Se presenta una conversión cíclica en la clase `Entero`.
Se recibe un _string_ el cual convierten a lista, para luego unir al misma lista en un _string_ (el cual será el mismo original) y finalmente convertirlo a un dato numérico.  
¿Motivo de la conversión cíclica? Este tipo de aportes no son `commit`s funcionales y me son bastante sospechosos. No se ve una lógica de programación en el desarrollo.

**Comment by dario-castano** [comment]
Se asigna al encargado de la clase Entero

**Comment by DanielBetancur** [comment]
El objetivo de esto es que la función exponencial nesecita usar una lista para poder tener recurrencia  y aplicar que la definición de exponencial como multiplicar un numero por si mismo n veces y la otra parte es por si no es una llamanda de exponencial devuelve un string

**Comment by cosmoscalibur** [comment]
Pase por alto referenciar `commit`s y ya no logro encontrar el historial en el cual aparece. Sin embargo no me refiero a lo que actualmente hay en el código de entero. De hecho es particular, que habiendo dos reportes corregidos (#2 y #3 -que asocia con el primero- respecto a dicho archivo, y ahora el #8), no hay reporte de dicha corrección en el historial del archivo. Aparentemente solo existe 1 `commit` sobre el archivo, al igual que solo un `commit` de @DanielBetancur siendo el encargado de dichas correcciones cuando mínimamente debería estar el historial asociado al reporte #2. ¿Hubo algún `rebase` en el repositorio?
